import '@/styles/globals.css'

import AuthProvider from '@/components/auth/AuthProvider'
import Footer from '@/components/navigation/Footer'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navigation/Navbar'
import { Toaster } from '@/components/ui/Toaster'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app and includes lots of goodies!',
}

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode
  authModal: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('bg-white text-slate-900 antialiased', inter.className)}>
      <body className='min-h-screen pt-12 bg-slate-50 antialiased'>
        <AuthProvider>
          <Navbar />

          {authModal}

          <div className='container max-w-7xl mx-auto h-full pt-12'>
            {children}
          </div>

          {/* <Footer /> */}
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
