import TRPCProvider from "@/app/_trpc/TRPCProvider";
import NavMenu from "@/components/Navmenu";
import AuthSessionProvider from "@/utils/AuthSessionProvider";
import type {Metadata} from "next";
import {getServerSession} from "next-auth";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Complete Next App",
	description: "Generated by complete next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession();

	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthSessionProvider session={session}>
					<TRPCProvider>
						<NavMenu />
						{children}
					</TRPCProvider>
				</AuthSessionProvider>
			</body>
		</html>
	);
}
